### ISSUE TITLE
correct use of degPCA

### ISSUE THREAD

**Issue by lpantano** [miRTop/mirgff3_shiny#6]
`    degPCA(assays(se)[[1]], metadata = colData(se), condition = columname, data = FALSE)`

**Comment by adriancbondia** [comment]
Puede ser así?
degPCA(assays(se)[[1]], metadata = colData(se), **condition = colnames(metadata)**, data = FALSE)

**Comment by lpantano** [comment]
tiene que ser colData(se). Siempre tienes que usar el `se` object una vez lo haz creado. Te da error?

**Comment by adriancbondia** [comment]
degPCA(assays(se)[[1]], metadata = colData(se), **condition = colnames(colData(se))**, data = FALSE)

Si, así funciona perfecto
